### ISSUE TITLE
Please add proper internationalization

### ISSUE THREAD

**Issue by deckerweb** [calvinmakes/church-pro-post-types#1]
Please make this plugin fully translateble!

Following stuff is missing:
- Textdomain loading function
- Textdomain & Path in plugin header
- Proper Textdomain for all strings & Gettext syntax

As for textdomain ist should be the plugin's slug so in this case: "community-pro-post-types"
Current use of "community_pro" should be all unified to "community-pro-post-types"

THANKS!! :)

**Comment by cjkoepke** [comment]
Thanks again ;) I'll add this in the next version. If you have experience with generating POT files for plugins, feel free to submit a pull request as well—it's a pain in my ass ;)

**Comment by deckerweb** [comment]
Thanks :)
If I'll find some time this weekend I try on a PR... :)

**Comment by deckerweb** [comment]
PR added :)
