### ISSUE TITLE
Change function prefix for "gfcptw_" stuff

### ISSUE THREAD

**Issue by deckerweb** [calvinmakes/church-pro-post-types#2]
This prefix "gfcptw_" is already used in @calliaweb's plugin, so if a user has her plugin active with yours it will break... :(

Best some prefix fitting better to yours, like "cppt_" or such... :-)

THANKS!

**Comment by cjkoepke** [comment]
Thanks for pointing this out! I will push it in the next version of the plugin.

**Comment by deckerweb** [comment]
PR added :)
